### ISSUE TITLE
Mostrar precio original

### ISSUE THREAD

**Issue by juansegnana** [meli-to-crypto/meli-to-crypto-extension#22]
Pienso que estaría bueno tener tanto el precio original como en el convertido a simple vista. Se me ocurre: 
1. Mostrar en un tooltip
Ej:
![image](https://user-images.githubusercontent.com/37079836/159190082-b0cd9aba-0891-4295-9040-e84fd1362316.png)
2. Mostrar abajo, en un tamaño reducido (con mejor estilo obvio).
![image](https://user-images.githubusercontent.com/37079836/159190279-66194fb5-973b-494f-be79-d5177e9a500a.png)

**Comment by andresgardiol** [comment]
El hover sería sobre el precio? 
Me copa bastante che.

En la lista podría estar la opción de volver a pesos también

**Comment by agustinsaldias** [comment]
No estaría nada mal, el precio original ahora se mantiene en los attr 'm2c-original' de cada elemento luego de #19 

La forma 1) con el tooltip permitiría mostrar el original de cada valor (precio original, descontado y cuotas) así que me gusta más personalmente

Como variación de 2), también se podría agregar en cada precio su original ARS más chiquito entre paréntesis a un lado.

![image](https://user-images.githubusercontent.com/3443149/159197373-a974f26c-45ba-4e5b-84ee-ac956978f0f5.png)

Aunque admito se hace un poco más cargado, tal vez no debería ser funcionamiento default sino por configuración
Capaz 3 opciones de 'display original':
- Sin precio original
- Solo precio principal
- Todos los precios

**Comment by andresgardiol** [comment]
Me gusta mas la opción 1 tambien, un buen uso para un tooltip-

> No estaría nada mal, el precio original ahora se mantiene en los attr 'm2c-original' de cada elemento luego de #19
> 
> La forma 1) con el tooltip permitiría mostrar el original de cada valor (precio original, descontado y cuotas) así que me gusta más personalmente
> 
> Como variación de 2), también se podría agregar en cada precio su original ARS más chiquito entre paréntesis a un lado.
> 
> ![image](https://user-images.githubusercontent.com/3443149/159197373-a974f26c-45ba-4e5b-84ee-ac956978f0f5.png)
> 
> Aunque admito se hace un poco más cargado, tal vez no debería ser funcionamiento default sino por configuración Capaz 3 opciones de 'display original':
> 
> * Sin precio original
> * Solo precio principal
> * Todos los precios

**Comment by MateoCerquetella** [comment]
Buena idea Juan, yo opto por la primera opción, es un UI mas limpio y el UX muchísimo mejor
