### ISSUE TITLE
Moneda preferida con conversion automatica

### ISSUE THREAD

**Issue by MateoCerquetella** [meli-to-crypto/meli-to-crypto-extension#23]
Buenas gente como están??

Queria comentar para ver que les parece tener una moneda favorita y que ya haga con la conversion automática a la hora de cargar la pagina de MELI.

Estoy actualmente haciendo el issue de [ejecutar el script al hacer el load de la pagina](https://github.com/ferminrp/meli-to-crypto/issues/9) y se me ocurrió esta idea.

Ya estuve averiguando y se puede guardar en forma sincronía cualquier data, eso significa que te queda guardada en el cloud con tu cuenta de google.

Podiamos poner como default la de ARS y con un select elegir la moneda preferida.

1. ![Screen Shot 2022-03-21 at 5 14 22 PM](https://user-images.githubusercontent.com/33433649/159356238-3f46528b-7d01-46bb-939a-e219e7efa5ff.png)2. 

2. ![Screen Shot 2022-03-21 at 5 17 15 PM](https://user-images.githubusercontent.com/33433649/159356656-08e30252-ee00-43b3-869d-ba1c5d48b430.png)
 
3. ![Screen Shot 2022-03-21 at 5 15 30 PM](https://user-images.githubusercontent.com/33433649/159356370-a5ea26e8-05c5-4a75-ae70-bb498ee91d69.png)

**Comment by ferminrp** [comment]
A favor con toda violencia.

Usaria como "favorita" la moneda que utilizo por ultima vez el flaco. Y si [pasamos al api de cryptoya](https://github.com/ferminrp/meli-to-crypto/issues/20#issuecomment-1072794756) con multiples exchanges, que favorita sea la combinacion de exchange + crypto.

**Comment by MateoCerquetella** [comment]
Perfecto me va, la API está buenísima tambien, una vez terminado esto podría hacer el refactor para que agarre esa API, total con lo que esta hecho con dos lineas lo cambias fácilmente!
