### ISSUE TITLE
Mostrar el dropdown como listado de monedas, no de pares

### ISSUE THREAD

**Issue by ferminrp** [meli-to-crypto/meli-to-crypto-extension#35]
Como dijo Nelson en el discord, el /ARS es redundante.

![image](https://user-images.githubusercontent.com/21282919/159944219-88fe2e6f-f4f8-4c64-9c3d-02864b03f038.png)

**Comment by MateoCerquetella** [comment]
Apruebo fuerte, tambien pondría un icono al lado de la crypto para que quede mejor UI

**Comment by MateoCerquetella** [comment]
De paso podríamos mejorar el UX/UI y ponerlo en otro issue, está simple lo cual esta perfecto pero ahora tenemos recursos para poder mejorarlo 🙌🏻
